apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    image.redhat.com/generate: "true" # TODO ??
    appstudio.openshift.io/pac-provision: request # TODO ??
  name: istio-pilot
spec:
  componentName: istio-pilot
  application: sail-operator
  build-nudges-ref:
    # TODO: does this automatically trigger the bundle build?
    # https://gitlab.cee.redhat.com/konflux/docs/users/-/blob/main/topics/02-getting-started/04-building-olm-products.md#building-operands-and-operators
    - sail-operator-metadata-bundle 
  source:
    git:
      url: https://github.com/asmigala/istio.git
      dockerfileUrl: docker/Dockerfile.konflux
      revision: konflux-wip
